### ISSUE TITLE
Adding missing weather effects

### ISSUE THREAD

**Issue by patf0rd** [DengSir/tdBattlePetScript#16]
It would be nice to see the missing weather effects Lightning Storm (203), Lightning Storm X (2320), and Toxic Gas (2350) added into snippets.lua in a future update.

**Comment by bloerwald** [comment]
All weather abilities (9.0.1.35213):

AbilityID | StateID | BattlePetStateLuaName
-- | -- | --
171 | 53 | Weather_BurntEarth
590 | 54 | Weather_ArcaneStorm
596 | 55 | Weather_Moonlight
257 | 56 | Weather_Darkness
454 | 57 | Weather_Sandstorm
205 | 58 | Weather_Blizzard
718 | 59 | Weather_Mud
229 | 60 | Weather_Rain
403 | 61 | Weather_Sunlight
203 | 62 | Weather_LightningStorm
2320 | 62 | Weather_LightningStorm
`-` | 63 | Weather_Windy
2350 | 316 | Weather_Toxic_Gas
