### ISSUE TITLE
Error During Log In - Any way to fix this by easily editing code?

### ISSUE THREAD

**Issue by ShadowMan1973** [DengSir/tdBattlePetScript#20]
Message: Interface\AddOns\tdBattlePetScript\UI\PetBattle.lua:208: '=' expected near 'self'
Time: Mon Aug  3 07:34:05 2020
Count: 6
Stack: Interface\AddOns\tdBattlePetScript\UI\PetBattle.lua:208: '=' expected near 'self'

Locals: <none>

**Comment by axc450** [comment]
Is this on beta?

**Comment by ShadowMan1973** [comment]
Release. Do not have my updater set to anything else

**Comment by axc450** [comment]
Had a look into this - I cant seem to reproduce ☹️ 
It could be a conflicting addon. I'd recommend reinstalling and then disabling addons and slowly re-enabling until you hit the issue again.
