### ISSUE TITLE
Shadowlands 9.0.1 error

### ISSUE THREAD

**Issue by yoshimo** [DengSir/tdBattlePetScript#23]
Message: ...Ons\tdBattlePetScript\Libs\tdGUI\Widget\DropMenu.lua line 33:
   attempt to call method 'SetBackdrop' (a nil value)
Debug:
   [string "=[C]"]: SetBackdrop()
   [string "@tdBattlePetScript\Libs\tdGUI\Widget\DropMenu.lua"]:33: ctor()
   [string "@tdBattlePetScript\Libs\tdGUI\Libs\LibClass-2.0\Class-2.0.lua"]:90:
      ...PetScript\Libs\tdGUI\Libs\LibClass-2.0\Class-2.0.lua:82
   [string "=(tail call)"]: ?
   [string "@tdBattlePetScript\Libs\tdGUI\Widget\DropMenu.lua"]:329

Message: ...Ons\tdBattlePetScript\UI\Widgets\AutoCompleteBox.lua line 25:
   attempt to call method 'SetBackdrop' (a nil value)
Debug:
   [string "=(tail call)"]: ?
   [string "@tdBattlePetScript\UI\Widgets\AutoCompleteBox.lua"]:25: ctor()
   [string "@tdBattlePetScript\Libs\tdGUI\Libs\LibClass-2.0\Class-2.0.lua"]:90:
      ...PetScript\Libs\tdGUI\Libs\LibClass-2.0\Class-2.0.lua:82
   [string "=(tail call)"]: ?
   [string "@tdBattlePetScript\UI\Widgets\ScriptEditor.lua"]:17: ctor()
   [string "@tdBattlePetScript\Libs\tdGUI\Libs\LibClass-2.0\Class-2.0.lua"]:90:
      ...PetScript\Libs\tdGUI\Libs\LibClass-2.0\Class-2.0.lua:82
   [string "=(tail call)"]: ?
   [string "@tdBattlePetScript\UI\MainPanel.lua"]:234: MakeBox()
   [string "@tdBattlePetScript\UI\MainPanel.lua"]:255:
      tdBattlePetScript\UI\MainPanel.lua:26
   [string "=[C]"]: ?
   [string "@Ace3\AceAddon-3.0\AceAddon-3.0.lua"]:70:
      Ace3\AceAddon-3.0\AceAddon-3.0.lua:65

**Comment by axc450** [comment]
There is a temp fix in: https://www.curseforge.com/wow/addons/tdbattlepetscript?comment=114
