### ISSUE TITLE
ElvUI skinning issue

### ISSUE THREAD

**Issue by MSav93** [DengSir/tdBattlePetScript#24]
This is an issue brought up on the curseforge page I'm just rewriting it here so it's tracked and resolved properly.

![image](https://user-images.githubusercontent.com/5080453/91844543-023f2480-ec9b-11ea-8fd0-9afd9fa38194.png)

A solution discovered by Minstril43 on curseforge involves not creating "ArtFrame2" if ElvUI is active and skinning the pet battle UI.
See workaround here: https://www.curseforge.com/wow/addons/tdbattlepetscript?comment=89

**Comment by sylvanas1408** [comment]
hi，it didn't work，can u upload your changed file：petbattle.lua，i amnot sure i changed it right

**Comment by bloerwald** [comment]
Duplicate of #50.
