### ISSUE TITLE
Packaging issue for curse 90001.01

### ISSUE THREAD

**Issue by justinkb** [DengSir/tdBattlePetScript#29]
It is packaged with the older version of the tdGUI lib

**Comment by GurliGebis** [comment]
Indeed - I have created a patch here that updates the tdGUI library to the newest version:

https://gist.github.com/GurliGebis/c59f86018ce417f71a4e9444ab0dcc1b

**Comment by DengSir** [comment]
I forgot to update pkg.yaml again, I decided to abandon it and use Travis and https://github.com/DengSir/wow-curse-tools
