### ISSUE TITLE
Issues with pet "Mr. Wiggles"

### ISSUE THREAD

**Issue by Gonzom** [DengSir/tdBattlePetScript#3]
Just found about this great addon!

I'm having an issue with Mr Wiggles. 
I change to this pet fine like this:
`change(Mr. Wiggles:126) `

But when I try to do something like this, it won't work:
`[self(Mr. Wiggles:126).active]`
Other pets do work. Might the "." in the name be causing this (this is the official name)?

**Comment by DengSir** [comment]
Fixed
