### ISSUE TITLE
Disconnect when Fight Starts

### ISSUE THREAD

**Issue by germyparker** [DengSir/tdBattlePetScript#34]
When I first enter a pet fight, I disconnect.  When I come back into the game I can start the fight normally and use the TD script.

**Comment by stornquist** [comment]
I have this issue as well. Start a fight, get DCed. Restart game and the first fight works fine, DC on the second fight.

**Comment by stornquist** [comment]
Turns out this is a problem with blizzard. start pet battles unmounted.
