### ISSUE TITLE
宠物对战界面和elvui美化有冲突 望解决 感谢

### ISSUE THREAD

**Issue by sylvanas1408** [DengSir/tdBattlePetScript#42]
![微信图片_20210302135839](https://user-images.githubusercontent.com/58397030/109740830-e21afe80-7c06-11eb-89e0-d788ade92ac2.png)
经测试，插件和elvui宠物界面美化有冲突，请问这个框如何去掉。。。。谢谢

**Comment by bloerwald** [comment]
Duplicate of #50.
