### ISSUE TITLE
Error code with enemy.ability

### ISSUE THREAD

**Issue by mutanzoom** [DengSir/tdBattlePetScript#48]
I get this error code when I paste this:
ability(Supercharge:208) [enemy.ability(Headbutt:376).duration<=4]

1x tdBattlePetScript\Core\Condition.lua:37: attempt to compare boolean with nil
[string "@tdBattlePetScript\Core\Condition.lua"]:37: in function <tdBattlePetScript\Core\Condition.lua:37>
[string "=(tail call)"]: ?
[string "=(tail call)"]: ?
[string "@tdBattlePetScript\Core\Director.lua"]:32: in function `Action'
[string "@tdBattlePetScript\Core\Director.lua"]:22: in function `Run'
[string "@tdBattlePetScript\UI\PetBattle.lua"]:312: in function `OnAutoButtonClick'
[string "@tdBattlePetScript\UI\PetBattle.lua"]:67: in function <tdBattlePetScript\UI\PetBattle.lua:66>

Locals:
a = false
b = nil
(*temporary) = nil
(*temporary) = "attempt to compare boolean with nil"

**That would be the scripts for the world quest: Caregiver Maximillian**
ability(Supercharge:208) [enemy.ability(Headbutt:376).duration<=4]
ability(170) [round=2]
ability(654) [self.aura(242).exists]
ability(117)
change(#2) [self(#1).dead]
change(#3) [self(#2).dead]
standby [self.aura(927).exists]
ability(204) [self.aura(207).exists]
ability(384)
ability(589)
ability(489)

What am I doing wrong? :(

**Comment by axc450** [comment]
Should be fixed now :)
