### ISSUE TITLE
Alternate Addon Providers (for WowUp/Ajour users)

### ISSUE THREAD

**Issue by Scryrz** [DengSir/tdBattlePetScript#53]
Now that Curseforge has revoked API access from third-party addon managers like WowUp and Ajour, are there currently any plans to host this addon elsewhere (Wago, WowInterface)? If not, would you be open to using BigWigs Packager to append formatted zips so that the aforementioned third-party addon clients can install directly from this repo?

[BigWigs Packager Action](https://github.com/BigWigsMods/packager)

**Comment by Poisonenvy2** [comment]
I second this :-)  Would love to see this addon hosted anywhere else other than Curse xx

**Comment by Rhinomer** [comment]
Wago would be best. There they are also supported and their work is paid!
And we can further update it with WowUp. Both sides won :)

**Comment by Xionyus** [comment]
Would love to see this anywhere other than curse as well. :)

**Comment by axc450** [comment]
I will try and host this somewhere else!

**Comment by bloerwald** [comment]
#57 adds support for CurseBreaker and any other add-on manager that can use GitHub releases.

**Comment by fraerie** [comment]
I have been using wago.io for addon management - it puts everything in the one place with your weak aura updates

**Comment by axc450** [comment]
The maintained version of this addon has support for multiple addon managers: https://www.curseforge.com/wow/addons/pet-battle-scripts
