### ISSUE TITLE
LUA Error in Prepatch

### ISSUE THREAD

**Issue by Xionyus** [DengSir/tdBattlePetScript#56]
4x Interface/AddOns/tdBattlePetScript/UI/MainPanel.lua:366: attempt to index field 'ScriptBox' (a nil value)
[string "@Interface/AddOns/tdBattlePetScript/UI/MainPanel.lua"]:366: in function `OnFontChanged'
[string "@Interface/AddOns/tdBattlePetScript/UI/MainPanel.lua"]:352: in function <Interface/AddOns/tdBattlePetScript/UI/MainPanel.lua:351>
[string "=[C]"]: ?
[string "@Interface/AddOns/ElvUI/Libraries/Core/Ace/AceAddon-3.0-13/AceAddon-3.0.lua"]:66: in function <...vUI/Libraries/Core/Ace/AceAddon-3.0/AceAddon-3.0.lua:61>
[string "@Interface/AddOns/ElvUI/Libraries/Core/Ace/AceAddon-3.0-13/AceAddon-3.0.lua"]:523: in function `EnableAddon'
[string "@Interface/AddOns/ElvUI/Libraries/Core/Ace/AceAddon-3.0-13/AceAddon-3.0.lua"]:536: in function `EnableAddon'
[string "@Interface/AddOns/ElvUI/Libraries/Core/Ace/AceAddon-3.0-13/AceAddon-3.0.lua"]:626: in function <...vUI/Libraries/Core/Ace/AceAddon-3.0/AceAddon-3.0.lua:611>
[string "=[C]"]: in function `LoadAddOn'
[string "@Interface/FrameXML/UIParent.lua"]:530: in function `UIParentLoadAddOn'
[string "@Interface/AddOns/Rarity/Core/Collections.lua"]:63: in function `ScanToys'
[string "@Interface/AddOns/Rarity/Core/Collections.lua"]:282: in function `ScanExistingItems'
[string "@Interface/AddOns/Rarity/Core.lua"]:175: in function `DoEnable'
[string "@Interface/AddOns/Rarity/Core.lua"]:151: in function <Interface/AddOns/Rarity/Core.lua:150>
[string "=[C]"]: ?
[string "@Interface/AddOns/ElvUI/Libraries/Core/Ace/AceAddon-3.0-13/AceAddon-3.0.lua"]:66: in function <...vUI/Libraries/Core/Ace/AceAddon-3.0/AceAddon-3.0.lua:61>
[string "@Interface/AddOns/ElvUI/Libraries/Core/Ace/AceAddon-3.0-13/AceAddon-3.0.lua"]:523: in function `EnableAddon'
[string "@Interface/AddOns/ElvUI/Libraries/Core/Ace/AceAddon-3.0-13/AceAddon-3.0.lua"]:626: in function <...vUI/Libraries/Core/Ace/AceAddon-3.0/AceAddon-3.0.lua:611>

**Comment by karmamuscle** [comment]
Got the same error as Xionyus and one more.

```
1x Interface/AddOns/tdBattlePetScript/UI/MainPanel.lua:365: attempt to index field 'ScriptBox' (a nil value)
[string "@Interface/AddOns/tdBattlePetScript/UI/MainPanel.lua"]:365: in function `OnFontChanged'
[string "@Interface/AddOns/tdBattlePetScript/UI/MainPanel.lua"]:351: in function <Interface/AddOns/tdBattlePetScript/UI/MainPanel.lua:350>
[string "=[C]"]: ?
[string "@Interface/AddOns/tdBattlePetScript/Libs/AceAddon-3.0-13/AceAddon-3.0.lua"]:70: in function <...tdBattlePetScript/Libs/AceAddon-3.0/AceAddon-3.0.lua:65>
[string "@Interface/AddOns/tdBattlePetScript/Libs/AceAddon-3.0-13/AceAddon-3.0.lua"]:527: in function `EnableAddon'
[string "@Interface/AddOns/tdBattlePetScript/Libs/AceAddon-3.0-13/AceAddon-3.0.lua"]:540: in function `EnableAddon'
[string "@Interface/AddOns/tdBattlePetScript/Libs/AceAddon-3.0-13/AceAddon-3.0.lua"]:630: in function <...tdBattlePetScript/Libs/AceAddon-3.0/AceAddon-3.0.lua:615>
```
```
1x Interface/AddOns/tdBattlePetScript/UI/MainPanel.lua:38: attempt to call method 'SetMinResize' (a nil value)
[string "@Interface/AddOns/tdBattlePetScript/UI/MainPanel.lua"]:38: in function <Interface/AddOns/tdBattlePetScript/UI/MainPanel.lua:26>
[string "=[C]"]: ?
[string "@Interface/AddOns/tdBattlePetScript/Libs/AceAddon-3.0-13/AceAddon-3.0.lua"]:70: in function <...tdBattlePetScript/Libs/AceAddon-3.0/AceAddon-3.0.lua:65>
[string "@Interface/AddOns/tdBattlePetScript/Libs/AceAddon-3.0-13/AceAddon-3.0.lua"]:498: in function `InitializeAddon'
[string "@Interface/AddOns/tdBattlePetScript/Libs/AceAddon-3.0-13/AceAddon-3.0.lua"]:623: in function <...tdBattlePetScript/Libs/AceAddon-3.0/AceAddon-3.0.lua:615>
```

**Comment by axc450** [comment]
I have a fix for this coming

**Comment by Gil-ER** [comment]
around 366 edit this line to add the ', ""'
self.ScriptBox:SetFont(Addon:GetSetting('editorFontFace'), Addon:GetSetting('editorFontSize'), "")

Also 3 places have:
...SetMinResize(a,b) and
...SetMaxResize(c,d)
they need to be changed to ...SetResizeBounds(a,b,c,d)

**Comment by axc450** [comment]
> around 366 edit this line to add the ', ""' self.ScriptBox:SetFont(Addon:GetSetting('editorFontFace'), Addon:GetSetting('editorFontSize'), "")
> 
> Also 3 places have: ...SetMinResize(a,b) and ...SetMaxResize(c,d) they need to be changed to ...SetResizeBounds(a,b,c,d)

I have a working build already, just beta testing. Should be uploaded to curse soon

**Comment by axc450** [comment]
Fixed and uploaded to Curse :)
