### ISSUE TITLE
Talent Frame won't open in combat

### ISSUE THREAD

**Issue by limpieza** [DengSir/tdBattlePetScript#61]
Hi, 

Since Dragonflight, I'm not able to open the talent frame window whenever I'm in combat.
An error message appear only in the chat "Interface action failed because of an Addon". 

I disabled all my others addons but TdBattleScript when testing.

Thanks for the addon and the updates :)

Limpi'

**Comment by axc450** [comment]
This issue is fixed in the maintained version of this addon: https://www.curseforge.com/wow/addons/pet-battle-scripts
