### ISSUE TITLE
Round.lua error

### ISSUE THREAD

**Issue by ghost** [DengSir/tdBattlePetScript#62]
NOTE: the below happens even when I only have Rematch and Tdbattlepetscript running.

After updating to the 10.0 version, this happens and I am unable to do anything in a fight:

2x ...terface/AddOns/tdBattlePetScript/Extension/Round.lua:12: table index is nil
[string "@Interface/AddOns/tdBattlePetScript/Extension/Round.lua"]:12: in function <...terface/AddOns/tdBattlePetScript/Extension/Round.lua:9>
[string "=[C]"]: ?
[string "@Interface/AddOns/Ace3/AceAddon-3.0-13/AceAddon-3.0.lua"]:66: in function <Interface/AddOns/Ace3/AceAddon-3.0/AceAddon-3.0.lua:61>
[string "@Interface/AddOns/Ace3/AceAddon-3.0-13/AceAddon-3.0.lua"]:523: in function `EnableAddon'
[string "@Interface/AddOns/Ace3/AceAddon-3.0-13/AceAddon-3.0.lua"]:536: in function `EnableAddon'
[string "@Interface/AddOns/Ace3/AceAddon-3.0-13/AceAddon-3.0.lua"]:536: in function `EnableAddon'
[string "@Interface/AddOns/Ace3/AceAddon-3.0-13/AceAddon-3.0.lua"]:626: in function <Interface/AddOns/Ace3/AceAddon-3.0/AceAddon-3.0.lua:611>
[string "=[C]"]: in function `LoadAddOn'
[string "@Interface/AddOns/PetTracker/addons/main/main.lua"]:46: in function `?'
[string "@Interface/AddOns/PetTracker/libs/WildAddon-1.0-1/WildAddon-1.0.lua"]:20: in function <...dOns/PetTracker/libs/WildAddon-1.0/WildAddon-1.0.lua:18>
[string "@Interface/AddOns/PetTracker/libs/WildAddon-1.0-1/WildAddon-1.0.lua"]:56: in function <...dOns/PetTracker/libs/WildAddon-1.0/WildAddon-1.0.lua:53>
[string "=[C]"]: ?
[string "@Interface/AddOns/Ace3/CallbackHandler-1.0-7/CallbackHandler-1.0.lua"]:24: in function <...Ons/Ace3/CallbackHandler-1.0/CallbackHandler-1.0.lua:20>
[string "@Interface/AddOns/Ace3/CallbackHandler-1.0-7/CallbackHandler-1.0.lua"]:59: in function `Fire'
[string "@Interface/AddOns/Ace3/AceEvent-3.0-4/AceEvent-3.0.lua"]:120: in function <Interface/AddOns/Ace3/AceEvent-3.0/AceEvent-3.0.lua:119>
[string "=[C]"]: in function `LoadAddOn'
[string "@Interface/FrameXML/UIParent.lua"]:530: in function `UIParentLoadAddOn'
[string "@Interface/FrameXML/UIParent.lua"]:665: in function `TimeManager_LoadUI'
[string "@Interface/FrameXML/UIParent.lua"]:1466: in function <Interface/FrameXML/UIParent.lua:1350>
[string "=[C]"]: ?

**Comment by axc450** [comment]
This issue is fixed in the maintained version of this addon: https://www.curseforge.com/wow/addons/pet-battle-scripts
