### ISSUE TITLE
Request: [self.hp>enemy.hp]

### ISSUE THREAD

**Issue by SilentSigns** [DengSir/tdBattlePetScript#7]
Recently was trying to set conditions for Life Exchange to only cast when your pet will gain health by comparing my pets health with the enemy pets health, but the only way to use hp compare in the API documentation is to use an absolute number.

The in-game editor accepts [self.hp>enemy.hp] but breaks the script entirely.

**Comment by Ennin** [comment]
use self.hp.high or self.hp.low
